#!/bin/bash
echo "hello world"
dir="img2017"              # Remove all dots.

for f in *.jpg                 # no need to use ls.
do
    filename=${f##*/}          # Use the last part of a path.
    extension=${f##*.}         # Remove up to the last dot.
    filename=${filename%.*}    # Remove from the last dot.
    echo "$filename $dir"
	
	newFileName=${filename:12} #remove everything before the 12th charactor
	newFileName=${newFileName#0*} #remove leading zeros
	echo $newFileName

	if [[ $filename =~  [0-9]+_* ]]; then     # if its a cam image
		mv "$filename.$extension" "$newFileName.$extension" # remove leading numbers leaving only date
	fi

done
