#!/bin/bash
echo "hello world"
dir=“nameModified”              # Remove all dots.

for f in *.jpg                 # no need to use ls.
do
    filename=${f##*/}          # Use the last part of a path.
    extension=${f##*.}         # Remove up to the last dot.
    filename=${filename%.*}    # Remove from the last dot.
    echo "$filename $dir"
	
	newFileName=$count
	echo $newFileName

	if [[ $filename -gt 94000002201 ]]; then     # If the directory exists
		mv "$filename.$extension" "a$filename.$extension" # Move file there.
	fi

done
